### PR TITLE
Restructuring to make developing more intents easier.

### PR DESCRIPTION
**Pull request by vqtran**
onIntent now only routes/delegates to IntentHandlers.
Common utilities for making Responses, and more!

### CODE REVIEW

**Comment by GabeLoins** [comment]
yay

**Comment by GabeLoins** [comment]
just making sure- have you tested this? Seems like a lot of changes and it would be a pain to commit this if it could cause problems.

A good test plan I've been using is upload;

help
how many sales are there
how many stores are there

Also- sometimes I'll upload a new jar and it won't appear for a few minutes. This isn't common but its good to be aware of.

**Comment by vqtran** [comment]
Just ran this, it works!

**Comment by GabeLoins** [comment]
okay lgtm

**Pull request merged**
